apiVersion: batch/v1
kind: Job
metadata:
  name: create-vdb-job
spec:
  template:
    spec:
      imagePullSecrets:
        - name: artifact-registry
      containers:
        - name: create-vdb-job
          image: joshsgoldstein/create-vdb-job:latest
          imagePullPolicy: Always 
      restartPolicy: Never
  backoffLimit: 4