apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: laszlo-rag-seldon-core-v2
spec:
  steps:
    - name: laszlo-rag-combine-question
      inputs:
      - laszlo-rag-seldon-core-v2.inputs.memory_id
      - laszlo-rag-seldon-core-v2.inputs.role
      - laszlo-rag-seldon-core-v2.inputs.content
    - name: laszlo-embed
      inputs:
      - laszlo-rag-seldon-core-v2
      tensorMap:
        laszlo-rag-seldon-core-v2.inputs.content: input
    - name: laszlo-vdb
      inputs:
      - laszlo-embed
    - name: laszlo-rag
      inputs:
      - laszlo-rag-seldon-core-v2
      - laszlo-vdb
      - laszlo-rag-combine-question
      tensorMap:
        laszlo-rag-seldon-core-v2.inputs.content: question
        laszlo-vdb.outputs.context: context
        laszlo-rag-combine-question.outputs.content: history
        laszlo-rag-combine-question.outputs.role: roles
    - name: laszlo-rag-combine-answer
      inputs:
      - laszlo-rag-seldon-core-v2.inputs.memory_id
      - laszlo-rag.outputs.role
      - laszlo-rag.outputs.content
  output:
    steps:
    - laszlo-rag
    # - vdb
    # - embed
    - laszlo-rag-combine-answer
